### ISSUE TITLE
Python: tuples with same content aren't always same object

### ISSUE THREAD

**Issue by dchudz** [EloiseRosen/WhatTheFSharp#1]
The second Python example says:

> An is comparison returns True if both names point to the same object in memory. Tuples are immutable and so **two tuples with the same contents are the same object**. In contrast, lists are mutable, so one empty list is not the same object as another empty list.

(Emphasis mine.)

This isn't correct:

```
>>> a = range(500)
>>> t1 = tuple(a)
>>> t2 = tuple(a)
>>> t1 is t2
False
>>> t1 == t2
True
```

**Comment by EloiseRosen** [comment]
Thank you! Updated
